server:
  port: 8888
#微服务工程一般都要配置一个唯一的应用名，将来作为微服务名称注入到eureka容器
spring:
  application:
    name: eureka-regist-center
#注册中心的url配置，可参考源码进行配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka #如果要搭建eureka集群，那么这里的url要配置另一个eureka的地址，每个eureka都这样配置，从而形成集群。配置好集群之后，如果之前所有的微服务都是注册到8888的eureka上，而8888挂掉，微服务之间仍能正常通信，因为集群中其他实例完成了续约等操作
  instance:
      lease-expiration-duration-in-seconds: 10 # 服务续约机制的过期时间，默认为90秒，即90之后还未检测到心跳，则服务过期，从服务列表移除，此处在开发阶段建议调小
      lease-renewal-interval-in-seconds: 5 # 服务续约机制的间隔时间，默认为30秒，即30秒检测一次所有服务是否还在，此处在开发阶段建议减小时间